### ISSUE TITLE
Looks like there is a bug in v0.1.1 but fixed in head.

### ISSUE THREAD

**Issue by a-c-m** [jeffbski/hapi-bunyan-lite#6]
When installing via
> "hapi-bunyan-lite": "git+https://github.com/jeffbski/hapi-bunyan-lite.git#v0.1.1"

I get : 

```/.../hapi-bunyan-lite/hapi-bunyan-lite.js:44
      .on('log', logEvent.bind(null, null)) // request is null
      ^

TypeError: Cannot read property 'on' of undefined
    at /.../hapi-bunyan-lite/hapi-bunyan-lite.js:44:7
    at [object Object].internals.Any._validateWithOptions (/.../hapi-bunyan-lite/node_modules/joi/lib/any.js:429:16)
    at [object Object].root.validate (/.../hapi-bunyan-lite/node_modules/joi/lib/index.js:102:23)
    at Object.exports.register (/.../hapi-bunyan-lite/hapi-bunyan-lite.js:21:7)
    at Object.target [as register] (/...node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/...node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/...node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/...node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at [object Object].module.exports.internals.Plugin.parent.auth.internals.Plugin.register.each [as register] (/...node_modules/hapi/lib/plugin.js:320:11)
    at Object.exports.register (/...plugins/ben-logger/index.js:110:10)```

**Comment by jeffbski** [comment]
Thanks. I have released updated the version to 0.2.0 to incorporate the latest changes.
